language: node_js
node_js:
- 6
- 7
cache: yarn
script:
- yarn run eslint
- yarn run flow
- yarn run test
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: GPWCNOj6YU6muzam2W5dQe0L6NQQ+u0r3A0nd9nT33/A786yq1RoJPUUaypxTkvX8B8lgtsXqOuPj1SYi/SR8x+fpBwCuM3/Pkt90/KgyYs+kOZ8uhGW+xP3PaiSZYuHc0XcDv8QyC1JBiemd0ofYcFJWAqxBZGafgzy89XFVL3u9ZoX8gdQaZZH4/hO5Nra3Jg9LxNakOhzbtTQ4ux5GVFgAVvRaKMtpq4MVy03n+1GnH5e2PxI12f+4UNIGTa3xcbo+dPdhu2zJVDEHWHQrlG5GhNVTbrdVe8OsMxx8v65kpbUCEGgpukzuyYbkKXCS/PPQliewG0IENe7QypXkipk3UTIi0Yl3uNUWIJjL/edZ/FsyrT4c5Ie/f8GPIt34mN7/kAWBy+g1nr7wgfI5AZXPr+itLREruRb+jRCa2f04I0VxRHLtzgi9TD9fjscsexkn0odTpjAUC4OcMbxw1rb+Ot51kKvZnwYQlZmUlwM5FY5WqEAziwO6Rt5kJh1ydkqGF0An9kgDKIJ+Eqk8580Sd3ZDTgkFHv1u6EK3EqASPjNQab48pX0363BBKXwBgDUmxhCL408fkMMwcU02fqD+BmybEAh1B1uyRc4sGnLuM5rrVMww7SqKEk9cihCZfUN7Al2L7YpAZhDldEpwmKtIFOQatfrmqzb1Be3sOs=
  on:
    tags: true
    repo: intel-hpdd/parsely
